# NER zero shot transfer to
# Selected wikiann languages
# MasakhaNER

_target_: trident.TridentDataModule
_recursive_: false

datamodule_cfg:
  remove_unused_columns: true
  keep_raw_dataset: false
  setup:
    _target_: trident.utils.data.setup
    _recursive_: false
  on_after_setup:
    _target_: src.tasks.token_classification.processor.on_after_setup
    max_length: 510
    tokenizer:
      _target_: transformers.AutoTokenizer.from_pretrained
      pretrained_model_name_or_path: ${module.model.pretrained_model_name_or_path}
    column_names:
      text: tokens
      label: ner_tags

dataloader_cfg:
  _target_: torch.utils.data.dataloader.DataLoader
  collate_fn:
    _target_: transformers.data.data_collator.DataCollatorForTokenClassification
    tokenizer:
      _target_: transformers.AutoTokenizer.from_pretrained
      pretrained_model_name_or_path: ${module.model.pretrained_model_name_or_path}
    max_length: 510
    padding: true
  train:
    batch_size: 4
    shuffle: true
  val:
    batch_size: 256
    shuffle: false
  test:
    batch_size: 256
    shuffle: false

dataset_cfg:
  _target_: datasets.load.load_dataset
  train:
    _datasets_:
      _en_:
          path: wikiann
          name: en
          split: train
      _ar_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: ar
          split: train
      _hu_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: hu
          split: train
      _ta_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: ta
          split: train
      _zh_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: zh
          split: train
      _sw_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: sw
          split: train
      _tr_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: tr
          split: train
      _fi_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: fi
          split: train
      _vi_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: vi
          split: train
      _ur_:
          _method_:
            shuffle:
              seed: ${data_seed}
            select:
              indices:
                _target_: builtins.range
                _args_:
                  - 0
                  - ${shots}
          path: wikiann
          name: ur
          split: train
  val:
    _datasets_:
      validation_wikiann_en:
        path: wikiann
        name: en
        split: validation
      test_wikiann_en:
        path: wikiann
        name: en
        split: test
      validation_wikiann_ar:
        path: wikiann
        name: ar
        split: validation
      test_wikiann_ar:
        path: wikiann
        name: ar
        split: test
      validation_wikiann_fi:
        path: wikiann
        name: fi
        split: validation
      test_wikiann_fi:
        path: wikiann
        name: fi
        split: test
      validation_wikiann_hu:
        path: wikiann
        name: hu
        split: validation
      test_wikiann_hu:
        path: wikiann
        name: hu
        split: test
      validation_wikiann_sw:
        path: wikiann
        name: sw
        split: validation
      test_wikiann_sw:
        path: wikiann
        name: sw
        split: test
      validation_wikiann_ta:
        path: wikiann
        name: ta
        split: validation
      test_wikiann_ta:
        path: wikiann
        name: ta
        split: test
      validation_wikiann_tr:
        path: wikiann
        name: tr
        split: validation
      test_wikiann_tr:
        path: wikiann
        name: tr
        split: test
      validation_wikiann_ur:
        path: wikiann
        name: ur
        split: validation
      test_wikiann_ur:
        path: wikiann
        name: ur
        split: test
      validation_wikiann_vi:
        path: wikiann
        name: vi
        split: validation
      test_wikiann_vi:
        path: wikiann
        name: vi
        split: test
      validation_wikiann_zh:
        path: wikiann
        name: zh
        split: validation
      test_wikiann_zh:
        path: wikiann
        name: zh
        split: test
  test:
    _datasets_:
      validation_wikiann_en:
        path: wikiann
        name: en
        split: validation
      test_wikiann_en:
        path: wikiann
        name: en
        split: test
      validation_wikiann_ar:
        path: wikiann
        name: ar
        split: validation
      test_wikiann_ar:
        path: wikiann
        name: ar
        split: test
      validation_wikiann_fi:
        path: wikiann
        name: fi
        split: validation
      test_wikiann_fi:
        path: wikiann
        name: fi
        split: test
      validation_wikiann_hu:
        path: wikiann
        name: hu
        split: validation
      test_wikiann_hu:
        path: wikiann
        name: hu
        split: test
      validation_wikiann_sw:
        path: wikiann
        name: sw
        split: validation
      test_wikiann_sw:
        path: wikiann
        name: sw
        split: test
      validation_wikiann_ta:
        path: wikiann
        name: ta
        split: validation
      test_wikiann_ta:
        path: wikiann
        name: ta
        split: test
      validation_wikiann_tr:
        path: wikiann
        name: tr
        split: validation
      test_wikiann_tr:
        path: wikiann
        name: tr
        split: test
      validation_wikiann_ur:
        path: wikiann
        name: ur
        split: validation
      test_wikiann_ur:
        path: wikiann
        name: ur
        split: test
      validation_wikiann_vi:
        path: wikiann
        name: vi
        split: validation
      test_wikiann_vi:
        path: wikiann
        name: vi
        split: test
      validation_wikiann_zh:
        path: wikiann
        name: zh
        split: validation
      test_wikiann_zh:
        path: wikiann
        name: zh
        split: test
      test_masakhaner_amh:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: amh
        split: test
      test_masakhaner_hau:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: hau
        split: test
      test_masakhaner_ibo:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: ibo
        split: test
      test_masakhaner_kin:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: kin
        split: test
      test_masakhaner_lug:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: lug
        split: test
      test_masakhaner_luo:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: luo
        split: test
      test_masakhaner_pcm:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: pcm
        split: test
      test_masakhaner_swa:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: swa
        split: test
      test_masakhaner_wol:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: wol
        split: test
      test_masakhaner_yor:
        _target_: src.tasks.token_classification.processor.load_maskhaner
        name: yor
        split: test

